# Generated by Django 3.0.8 on 2020-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'planet',
                'verbose_name_plural': 'planets',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'productor',
                'verbose_name_plural': 'productors',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('year', models.IntegerField(verbose_name='name')),
                ('director', models.CharField(max_length=100, verbose_name='director')),
                ('opening_crawl', models.CharField(max_length=500, verbose_name='opening_clawl')),
                ('characters', models.ManyToManyField(blank=True, to='api.Character', verbose_name='characters')),
                ('planets', models.ManyToManyField(blank=True, to='api.Planet', verbose_name='planets')),
                ('productors', models.ManyToManyField(blank=True, to='api.Productor', verbose_name='productors')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
